### PR TITLE
LPS-61337 SF - use from/to instead of source/destination for consistency with remote service

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Bejond,

I'm sending you the pull as @adolfopa asked

### CODE REVIEW

**Comment by bejondshao** [comment]
Hi sergiogonzalez,

I'm looking into it.

**Comment by sergiogonzalez** [comment]
thx @bejondshao . If everything is working feel free to send it to Brian.

cc/ @adolfopa

**Comment by bejondshao** [comment]
@sergiogonzalez , would you send it to Brian please? Brian might not accept pull request from me.

Thanks

**Comment by bejondshao** [comment]
Hi @adolfopa ,

I tried to backport this to ee branch for customer. But it seems the new method you created and it's API is totally different from ee branch. Would you backport it to ee branch ?

Thanks

**Comment by bejondshao** [comment]
Hi @adolfopa ,

I've backported it successfully. It works just like you did. Once the exception happens, the all moving process would rollback, the file system is not changed.

https://patcher.liferay.com/group/guest/patching/-/osb_patcher/fixes/20414916

**Comment by sergiogonzalez** [comment]
Sent to Brian here https://github.com/brianchandotcom/liferay-portal/pull/33707

**Pull request closed without merging**
